version: '3'
services:

  web: # Web Interface
    image: killrvideo/killrvideo-web:3.0.1
    ports:
      - "3000:3000" # Exposes port to be available externally
    depends_on:
      - backend # Needs Backend to be running
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging
    labels:
      kompose.service.type: nodeport # Adds a label for Kompose to expose service externally

  backend: # KillrVideo Backend 
    image: killrvideo/killrvideo-java:3.0.1
    ports:
      - "50101:50101" # Exposes port to be available. Kompose tool needs that to create a k8s service and make backend available for other services.
    depends_on:
      - dse  # Needs DSE to be running
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging
      KILLRVIDEO_DSE_CONTACT_POINTS: dse

  studio:  # Datastax Studio provides convenient web interface to work directly with the Apache Cassandra or DataStax Enterprise
    image: datastax/dse-studio:6.7.0
    ports:
      - "9091:9091" # Exposes port to be available externally
    depends_on:
      - dse # Needs DSE to be running
    environment:
      DS_LICENSE: accept
    labels:
      kompose.service.type: nodeport # Adds a label for Kompose to expose service externally

  dse: # DataStax Enterprise Database
    image: datastax/dse-server:6.7.0
    command: [ -s -g ] # Run with Search and Graph capabilities enabled
    ports: # Exposes ports to be available. Kompose tool needs that to create a k8s service and make backend available for other services.
      - "9042:9042" # Exposes DSE port
      - "8983:8983" # Exposes DSE Search port
      - "8182:8182" # Exposes DSE Graph port
    environment:
      DS_LICENSE: accept # Accept licence on start
    cap_add:
      - IPC_LOCK # Allow DSE to lock memory with mlock
    ulimits:
      memlock: -1

  dse-config: # One-Time Bootstrap Container, configures DSE to have required keyspaces etc.
    image: killrvideo/killrvideo-dse-config:3.0.0
    depends_on:
      - dse # Needs DSE to be running
    restart: on-failure # Kompose needs that to create dse-config as a pod, not a deployment. DSE-Config deployment is not needed as we run it only once.

  generator: # Sample Data Generator, imitates behaviour of users on the killrVideo website. Adds comments and rates videos, upload new videos and so on.
    image: killrvideo/killrvideo-generator:3.0.1
    depends_on:
      - backend # Needs Backend to be running
    environment:
      KILLRVIDEO_LOGGING_LEVEL: debug # More logging
      KILLRVIDEO_YOUTUBE_API_KEY: AIzaSyAFBSo98gf7I2-ipLx7K7beE2hAG5GTVeU
